export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILED',
  CODE_RECEIVED: 'CODE_RECEIVED',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  USER_DATA: 'USER_DATA',
  INITIAL_STATE: 'INITIAL_STATE',
  USER_OBJECT: 'USER_OBJECT',
};
