export const bookingConstants = {
  GET_SERVICES: 'GET_SERVICES',
  SELECT_SERVICE: 'SELECT_SERVICE',
  SELECT_TIME: 'SELECT_TIME',
  SELECT_LOCATION: 'SELECT_LOCATION',
  BOOKING_REQUEST: 'BOOKING_REQUEST',
  BOOKING_SUCCESS: 'BOOKING_SUCCESS',
  BOOKING_FAILURE: 'BOOKING_FAILURE',
};
