export const bookingConstants = {
  BOOKING_REQUEST: 'BOOKING_REQUEST',
  BOOKING_SUCCESS: 'BOOKING_SUCCESS',
  BOOKING_FAILURE: 'BOOKING_FAILURE',
  BOOKING_DATA: 'BOOKING_DATA',
  GET_USER_BOOKING: 'GET_USER_BOOKING',
  GET_BOOKING_LOG: 'GET_BOOKING_LOG'
};
